### ISSUE TITLE
Bug: nics in vm

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/client#123]
# TODO: BUG: nics seems unexpected argument
            vm_id = cloud_provider.boot_vm(kwargs["name"],
                                           kwargs["image"],
                                           kwargs["flavor"],
                                           key=kwargs["key_name"],
                                           secgroup=kwargs["secgroup_list"],
                                           nics=nics)

**Comment by gouravshenoy** [comment]
Hello Professor,

We need ```nics``` argument while starting VM in ```kilo``` cloud. This is because in Kilo there are multiple network interfaces, and we need to spawn up a VM on one of those interfaces (fg478-net in our case).

In Juno, we boot a new VM on the default network interface in nova,

Hence, for Kilo we have the ```nics=nics``` argument to the ```nova boot``` command.

**Comment by laszewsk** [comment]
looks like its not part of definition. thEre should not be an error coming from pycharm inspect about it.

**Comment by laszewsk** [comment]
def boot_vm(self, name, image=None, flavor=None, cloud="India", key=None,
            secgroup=None, meta=None):
This also says the signature is mismtched. We need to have the signatures consitant, if nics is requiresd why not add it to the base method and have nics=None ?

**Comment by gouravshenoy** [comment]
Modified the ```CloudProviderOpenStackAPI.py``` and the ```CloudProviderBase.py``` classes to include ```nics``` argument (default to None).

Resolves the PyCharm inspect error. Closing this issue.
