### ISSUE TITLE
Command: register: install:certificate is not copied on cm register rc india

### ISSUE THREAD

**Issue by paulo-chagas** [cloudmesh/client#3]
When retrieve a rc file from a remote machine we need to check if the certificate is being specified. If it is not specified we need to copy 

Maybe we just copy the entire directory

**Comment by laszewsk** [comment]
This is probably fixed by now, but we need to use the dir copy. The installation from india needs to be checked so that it uses the dir copy.

devise strategy on what to do if dir and/or files in dir already are there.

I suggest you list all files that are already there and ask 

Do you want to replace all files? (y/n) use yn_choice function

if not you ask each file in the dir indivifually,

a --force flag just overwrites and does not ask question

**Comment by ehdsouza** [comment]
The certificate is copied to the correct directory ie ~/.cloudmesh/clouds/india/juno

Also, to copy the certificate explicitly, can use:
cm register india ~/.cloudmesh/clouds/india/juno/cacert.pem
